import {
  AdminAgentRunSchema,
  AdminConversationFilterSchema,
  AdminConversationListSchema,
  AdminConversationSummarySchema,
  AdminDashboardSessionSchema,
  AdminEventListSchema,
  AdminFailureListSchema,
  AdminFailureSchema,
  AdminHandoffFilterSchema,
  AdminHandoffListSchema,
  AdminHandoffSchema,
  AdminMessageListSchema,
  AdminOverviewSchema,
  AdminRunFilterSchema,
  AdminRunListSchema,
  AdminTokenClaimsSchema,
} from './schemas.js';

export const adminSchemaArtifacts = {
  'agent-run': AdminAgentRunSchema,
  'conversation-filter': AdminConversationFilterSchema,
  'conversation-list': AdminConversationListSchema,
  'conversation-summary': AdminConversationSummarySchema,
  'dashboard-session': AdminDashboardSessionSchema,
  'event-list': AdminEventListSchema,
  failure: AdminFailureSchema,
  'failure-list': AdminFailureListSchema,
  'handoff-filter': AdminHandoffFilterSchema,
  handoff: AdminHandoffSchema,
  'handoff-list': AdminHandoffListSchema,
  'message-list': AdminMessageListSchema,
  overview: AdminOverviewSchema,
  'run-filter': AdminRunFilterSchema,
  'run-list': AdminRunListSchema,
  'token-claims': AdminTokenClaimsSchema,
} as const;
